name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-cb:
    runs-on: codebuild-test-pipeline-${{ github.run_id }}-${{ github.run_attempt }}
    container: public.ecr.aws/docker/library/node:24.11.1
    # runs-on: ubuntu-latest
    # runs-on: self-hosted

    services:
      postgres:
        # image: postgres:15
        image: public.ecr.aws/docker/library/postgres:15.15-alpine
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: codebuild_pipeline_integration
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier
        run: npm run format:check

      - name: Lint Code
        run: npm run lint

      - name: Security Audit
        run: npm audit --audit-level=high

      - name: Sleep 30 seconds
        run: sleep 30

      - name: Build Project
        run: npm run build

      - name: Run Migrations
        env:
          DATABASE_URL: postgres://postgres:${{ secrets.DB_PASSWORD }}@postgres:5432/codebuild_pipeline_integration?schema=public
          # DATABASE_URL: postgres://postgres:${{ secrets.DB_PASSWORD }}@localhost:5432/codebuild_pipeline_integration?schema=public
        run: npx prisma migrate deploy

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:${{ secrets.DB_PASSWORD }}@postgres:5432/codebuild_pipeline_integration?schema=public
          # DATABASE_URL: postgres://postgres:${{ secrets.DB_PASSWORD }}@localhost:5432/codebuild_pipeline_integration?schema=public
        run: npm test

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/lcov.info

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  # sonar-scan:
  #   needs: build-and-test-cb
  #   # runs-on: ubuntu-latest
  #   # runs-on: self-hosted
  #   runs-on: codebuild-test-pipeline-${{ github.run_id }}-${{ github.run_attempt }}
  #   # container: public.ecr.aws/docker/library/node:24.11.1
  #   environment:
  #     name: manual-approval
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Download Coverage
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: coverage
  #         path: coverage

  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
