name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-cb:
    runs-on: codebuild-test-pipeline-${{ github.run_id }}-${{ github.run_attempt }}
    # runs-on: ubuntu-latest

    services:
      postgres:
        # image: postgres:15
        image: public.ecr.aws/docker/library/postgres:15.15-alpine
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: codebuild_pipeline_integration
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Create network
        run: |
          echo -e "CONTAINER ID\tNAME\tNETWORK MODE\tNETWORKS"
          for cid in $(docker ps -q); do
            name=$(docker inspect -f '{{.Name}}' "$cid" | sed 's/\///')
            netmode=$(docker inspect -f '{{.HostConfig.NetworkMode}}' "$cid")

            # Extract all attached Docker networks
            networks=$(docker inspect -f '{{range $k, $v := .NetworkSettings.Networks}}{{printf "%s " $k}}{{end}}' "$cid")

            echo -e "${cid}\t${name}\t${netmode}\t${networks}"
          done

      - name: Debug commands
        run: |
          docker ps
          docker image ls
          docker network ls

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier
        run: npm run format:check

      - name: Build Project
        run: npm run build

      - name: Run Migrations
        env:
          DATABASE_URL: postgres://postgres:${{ secrets.DB_PASSWORD }}@localhost:5432/codebuild_pipeline_integration?schema=public
        run: npx prisma migrate deploy

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:${{ secrets.DB_PASSWORD }}@localhost:5432/codebuild_pipeline_integration?schema=public
        run: npm test
